apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: amael-ia  # <-- CORREGIDO
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets: []
      containers:
      - name: backend-container
        image: localhost:32000/backend-ia:0.3.1 #<-- Asegúrate que esta es tu última versión
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        # --- SECCIÓN ENV CORRECTAMENTE ANIDADA ---
        env:
          # ... VAriable de TensorFlow2
          - name: TF_SERVING_URL
            value: "http://tf-serving-service:8501/v1/models/imagenet_classifier:predict"
          # Secretos de Google OAuth
          - name: GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: google-auth-secret
                key: client_id
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: google-auth-secret
                key: client_secret
          # Claves para JWT y Sesión
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: google-auth-secret
                key: jwt_secret_key
          - name: SESSION_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: google-auth-secret
                key: session_secret_key
          # Lista blanca de usuarios desde ConfigMap
          - name: ALLOWED_EMAILS_CSV
            valueFrom:
              configMapKeyRef:
                name: allowed-users-configmap
                key: ALLOWED_EMAILS_CSV
        volumeMounts:
        - name: chroma-storage
          mountPath: /chroma_data
      volumes:
        - name: chroma-storage
          persistentVolumeClaim:
            claimName: chroma-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: amael-ia
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
  
