apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tf-model-pvc
  namespace: amael-ia
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi # Suficiente para el modelo