# command-executor-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-executor-deployment
  namespace: amael-ia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: command-executor
  template:
    metadata:
      labels:
        app: command-executor
    spec:
      # --- ASIGNAR LA SERVICEACCOUNT CON PERMISOS LIMITADOS ---
      serviceAccountName: command-executor-sa
      containers:
      - name: command-executor
        image: localhost:32000/command-executor:0.0.1
        ports:
        - containerPort: 8001
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: command-executor-service
  namespace: amael-ia
spec:
  selector:
    app: command-executor
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001

