apiVersion: v1
kind: Service
metadata:
  name: productivity-service
  namespace: amael-ia
spec:
  # ClusterIP expone el servicio solo dentro del clúster
  type: ClusterIP
  selector:
    app: productivity-service
  ports:
    - protocol: TCP
      port: 8001       # El puerto que el Service expone
      targetPort: 8001 # El puerto en el contenedor al que se redirige el tráfico